#!/usr/bin/env bun
import { access, mkdir, readdir } from "node:fs/promises";
import { join } from "node:path";
import { SetupWizard, loadConfig } from "./config/index.js";
import { MissionRunner } from "./executor/index.js";
import { type MissionPlanInput, discoverInfrastructure, generateMissionArtifacts } from "./planner/index.js";
import { getNextMilestone, readFeatures, readValidationState, writeMissionState } from "./state/index.js";
import { gitInit, isGitRepo } from "./utils/index.js";

const USAGE = `
pi-missions - autonomous development mission orchestrator

Usage:
  pi-missions new [title]
  pi-missions resume
  pi-missions status
  pi-missions list
  pi-missions setup [--provider <name>] [--api-key <key>] [--skip-validation]
  pi-missions --help
`.trim();

interface ParsedArgs {
	command: string;
	positionals: string[];
	flags: Record<string, string | boolean>;
}

function parseArgs(argv: string[]): ParsedArgs {
	const [command = "--help", ...rest] = argv;
	const positionals: string[] = [];
	const flags: Record<string, string | boolean> = {};

	for (let index = 0; index < rest.length; index += 1) {
		const token = rest[index] ?? "";
		if (!token.startsWith("--")) {
			positionals.push(token);
			continue;
		}

		const key = token.slice(2);
		const next = rest[index + 1];
		if (!next || next.startsWith("--")) {
			flags[key] = true;
			continue;
		}
		flags[key] = next;
		index += 1;
	}

	return { command, positionals, flags };
}

async function pathExists(path: string): Promise<boolean> {
	try {
		await access(path);
		return true;
	} catch {
		return false;
	}
}

function buildDefaultPlan(title: string): MissionPlanInput {
	return {
		title,
		description: `Mission generated by pi-missions: ${title}`,
		milestones: [{ name: "foundation", description: "Initial implementation milestone." }],
		features: [
			{
				id: "initial-task",
				description: "Implement the first planned slice from user goals.",
				skillName: "dev-worker",
				milestone: "foundation",
				preconditions: [],
				expectedBehavior: ["Implements the requested behavior."],
				verificationSteps: ["bun test --timeout 120000", "bun run check", "bun run lint"],
				fulfills: ["VAL-PLAN-001"],
				status: "pending",
			},
		],
		validationAssertions: [
			{
				id: "VAL-PLAN-001",
				title: "Initial feature behavior is implemented",
				description: "The generated initial task behavior is present.",
				evidence: "Command output and tests demonstrate behavior.",
				area: "Generated",
			},
		],
		testingStrategy: "Run focused tests during execution and full checks at milestone boundaries.",
	};
}

async function cmdNew(positionals: string[], cwd: string): Promise<void> {
	const config = await loadConfig(cwd);
	const missionTitle = positionals.join(" ").trim() || "New Mission";
	const missionDir = config.missionDir;

	if (!isGitRepo(cwd)) {
		gitInit(cwd);
	}

	await mkdir(missionDir, { recursive: true });
	const discovery = await discoverInfrastructure(cwd);
	const plan = buildDefaultPlan(missionTitle);
	if (discovery.availablePorts.length > 0) {
		plan.description += ` Detected in-use ports: ${discovery.availablePorts.join(", ")}.`;
	}

	await generateMissionArtifacts(plan, cwd, missionDir);
	await writeMissionState(missionDir, {
		missionId: `mis_${Date.now().toString(36)}`,
		state: "running",
		workingDirectory: cwd,
		currentFeatureId: null,
		currentWorkerSessionId: null,
		createdAt: new Date().toISOString(),
		updatedAt: new Date().toISOString(),
	});

	process.stdout.write(`Created mission "${missionTitle}" at ${missionDir}\n`);
	process.stdout.write(`Run "pi-missions resume" to start execution.\n`);
}

async function cmdResume(cwd: string): Promise<void> {
	const config = await loadConfig(cwd);
	const features = await readFeatures(config.missionDir);
	if (features.length === 0) {
		throw new Error(`No mission found at ${config.missionDir}. Run "pi-missions new" first.`);
	}

	const runner = new MissionRunner();
	await runner.run(config.missionDir, { targetDir: cwd, defaultModel: config.defaultModel });
	process.stdout.write("Mission execution completed.\n");
}

async function cmdStatus(cwd: string): Promise<void> {
	const config = await loadConfig(cwd);
	const features = await readFeatures(config.missionDir);
	if (features.length === 0) {
		process.stdout.write("No mission found.\n");
		return;
	}

	const validationState = await readValidationState(config.missionDir);
	const counts = {
		pending: features.filter((feature) => feature.status === "pending").length,
		inProgress: features.filter((feature) => feature.status === "in_progress").length,
		completed: features.filter((feature) => feature.status === "completed").length,
		failed: features.filter((feature) => feature.status === "failed").length,
		cancelled: features.filter((feature) => feature.status === "cancelled").length,
	};
	const nextMilestone = getNextMilestone(features) ?? "none";
	const assertionStatuses = Object.values(validationState.assertions).reduce(
		(acc, assertion) => {
			acc[assertion.status] = (acc[assertion.status] ?? 0) + 1;
			return acc;
		},
		{} as Record<string, number>,
	);

	process.stdout.write(`Mission directory: ${config.missionDir}\n`);
	process.stdout.write(
		`Features: total=${features.length} pending=${counts.pending} in_progress=${counts.inProgress} completed=${counts.completed} failed=${counts.failed} cancelled=${counts.cancelled}\n`,
	);
	process.stdout.write(`Current milestone: ${nextMilestone}\n`);
	process.stdout.write(`Validation: ${JSON.stringify(assertionStatuses)}\n`);
}

async function listMissionDirs(cwd: string, missionDir: string): Promise<string[]> {
	const candidates = new Set<string>();
	if (await pathExists(join(missionDir, "features.json"))) {
		candidates.add(missionDir);
	}

	const missionsRoot = join(cwd, ".pi-missions", "missions");
	if (await pathExists(missionsRoot)) {
		const entries = await readdir(missionsRoot, { withFileTypes: true });
		for (const entry of entries) {
			if (!entry.isDirectory()) {
				continue;
			}
			const missionPath = join(missionsRoot, entry.name);
			if (await pathExists(join(missionPath, "features.json"))) {
				candidates.add(missionPath);
			}
		}
	}

	return Array.from(candidates);
}

async function cmdList(cwd: string): Promise<void> {
	const config = await loadConfig(cwd);
	const missionDirs = await listMissionDirs(cwd, config.missionDir);
	if (missionDirs.length === 0) {
		process.stdout.write("No missions found.\n");
		return;
	}

	process.stdout.write("Missions:\n");
	for (const missionDir of missionDirs) {
		const features = await readFeatures(missionDir);
		const completed = features.filter((feature) => feature.status === "completed").length;
		process.stdout.write(`- ${missionDir} (${completed}/${features.length} completed)\n`);
	}
}

async function cmdSetup(parsed: ParsedArgs, cwd: string): Promise<void> {
	const wizard = new SetupWizard();
	const result = await wizard.run({
		cwd,
		providerOverride: typeof parsed.flags.provider === "string" ? parsed.flags.provider : undefined,
		apiKeyOverride: typeof parsed.flags["api-key"] === "string" ? parsed.flags["api-key"] : undefined,
		skipValidation: parsed.flags["skip-validation"] === true,
	});
	process.stdout.write(`Setup complete for provider ${result.provider}.\n`);
}

export async function runCli(argv: string[] = process.argv.slice(2), cwd: string = process.cwd()): Promise<void> {
	const parsed = parseArgs(argv);
	switch (parsed.command) {
		case "--help":
		case "-h":
		case "help":
			process.stdout.write(`${USAGE}\n`);
			return;
		case "new":
			await cmdNew(parsed.positionals, cwd);
			return;
		case "resume":
			await cmdResume(cwd);
			return;
		case "status":
			await cmdStatus(cwd);
			return;
		case "list":
			await cmdList(cwd);
			return;
		case "setup":
			await cmdSetup(parsed, cwd);
			return;
		default:
			throw new Error(`Unknown command "${parsed.command}". Use --help for usage.`);
	}
}

if (import.meta.main) {
	try {
		await runCli();
	} catch (error) {
		process.stderr.write(`${(error as Error).message}\n`);
		process.exitCode = 1;
	}
}
